import "./globals.css"
import "katex/dist/katex.min.css"

import type { Metadata } from "next"
import type { JSX } from "react/jsx-runtime"

import { fontVariables } from "./fonts"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: LayoutProps<"/">): JSX.Element {
  return (
    <html lang="en" className={`${fontVariables} h-full antialiased`}>
      <body className="flex min-h-full flex-col">{children}</body>
    </html>
  )
}
