/**
 * Downloads LXGW WenKai (Simplified Chinese) from the upstream GitHub release
 * and splits it into unicode-range woff2 chunks so browsers only fetch the
 * glyphs a page uses. Google Fonts only carries the TC variant.
 *
 * Usage: bun fonts:wenkai [tag] [--force] [--dry-run]   (see --help)
 */

import { createHash } from "node:crypto"
import { rmSync } from "node:fs"
import {
  readdir,
  readFile,
  rename,
  rm,
  stat,
  unlink,
  writeFile,
} from "node:fs/promises"
import path from "node:path"
import { parseArgs, ParseArgsConfig } from "node:util"

const REPO = "lxgw/LxgwWenKai"
const ASSET = "LXGWWenKai-Regular.ttf"
const ROOT = path.resolve(import.meta.dirname, "..")
const SCRIPT = path.relative(ROOT, import.meta.filename)
const OUT_DIR = path.join(ROOT, "src/fonts/lxgw-wenkai")
const TMP_DIR = `${OUT_DIR}.tmp`
const CSS_FILE = "lxgw-wenkai.css"

const USAGE = `Usage: bun fonts:wenkai [tag] [options]

Downloads ${ASSET} from ${REPO} and splits it into woff2 chunks in
src/fonts/lxgw-wenkai. Defaults to the latest release.

Options:
  -f, --force    Regenerate even if the output is already at this release
  -n, --dry-run  Show what would be downloaded without writing anything
  -h, --help     Show this help

Set GITHUB_TOKEN to avoid GitHub API rate limits.`

const CONFIG = {
  options: {
    force: { type: "boolean", short: "f" },
    "dry-run": { type: "boolean", short: "n" },
    help: { type: "boolean", short: "h" },
  },
  allowPositionals: true,
} as const satisfies ParseArgsConfig

function fail(message: string): never {
  console.error(`error: ${message}`)
  process.exit(1)
}

function parseCli(): ReturnType<typeof parseArgs<typeof CONFIG>> {
  try {
    return parseArgs(CONFIG)
  } catch (error) {
    fail(`${(error as Error).message}\n\n${USAGE}`)
  }
}

const { values, positionals } = parseCli()
if (values.help) {
  console.log(USAGE)
  process.exit(0)
}
if (positionals.length > 1) {
  fail(`expected at most one tag, got: ${positionals.join(" ")}`)
}
const [tag] = positionals

const mb = (bytes: number) => `${(bytes / 1024 / 1024).toFixed(1)} MB`

async function get(
  url: string,
  headers: Record<string, string> = {},
): Promise<Response> {
  const res = await fetch(url, { headers })
  if (res.ok) return res
  const hint =
    res.status === 403 || res.status === 429 ?
      " (rate limited? set GITHUB_TOKEN)"
    : res.status === 404 && tag ? ` (is "${tag}" a release tag in ${REPO}?)`
    : ""
  fail(`GET ${url} → ${res.status} ${res.statusText}${hint}`)
}

/** Release tag recorded in the header of the existing CSS file, if any. */
async function currentTag(): Promise<string | undefined> {
  try {
    const css = await readFile(path.join(OUT_DIR, CSS_FILE), "utf8")
    return css.match(/^\/\* \S+ (\S+), generated by/)?.[1]
  } catch {
    return undefined
  }
}

const token = process.env.GITHUB_TOKEN
const releaseUrl = `https://api.github.com/repos/${REPO}/releases/${tag ? `tags/${tag}` : "latest"}`
const release = (await (
  await get(releaseUrl, {
    Accept: "application/vnd.github+json",
    ...(token ? { Authorization: `Bearer ${token}` } : {}),
  })
).json()) as {
  tag_name: string
  assets: {
    name: string
    size: number
    digest: string | null
    browser_download_url: string
  }[]
}
const asset = release.assets.find((a) => a.name === ASSET)
if (!asset) fail(`${ASSET} not found in ${REPO} ${release.tag_name}`)

const current = await currentTag()
if (current === release.tag_name && !values.force) {
  console.log(`Already at ${current}; pass --force to regenerate`)
  process.exit(0)
}

if (values["dry-run"]) {
  console.log(
    `Would replace ${current ?? "nothing"} with ${ASSET} ${release.tag_name}` +
      `(${mb(asset.size)})\n` +
      `  from ${asset.browser_download_url}\n` +
      `  into ${OUT_DIR}`,
  )
  process.exit(0)
}

console.log(`Downloading ${ASSET} ${release.tag_name} (${mb(asset.size)})`)
const input = new Uint8Array(
  await (await get(asset.browser_download_url)).arrayBuffer(),
)

if (asset.digest) {
  const actual = `sha256:${createHash("sha256").update(input).digest("hex")}`
  if (actual !== asset.digest) {
    fail(`checksum mismatch: expected ${asset.digest}, got ${actual}`)
  }
} else {
  console.warn(`warning: no digest published for ${ASSET}; skipping checksum`)
}

// Split into a sibling directory and swap only on success so a failed run
// preserves existing files.
console.log("Splitting")
await rm(TMP_DIR, { recursive: true, force: true })
const onInterrupt = () => {
  rmSync(TMP_DIR, { recursive: true, force: true })
  process.exit(130)
}
process.once("SIGINT", onInterrupt)
try {
  // Import lazily to hide cn-font-split banner for --help, --dry-run, and
  // error output.
  const { fontSplit } = await import("cn-font-split")
  await fontSplit({
    input,
    outDir: TMP_DIR,
    css: {
      fontFamily: "LXGW WenKai",
      fontWeight: "400",
      fontDisplay: "swap",
      fileName: CSS_FILE,
    },
    testHtml: false,
    reporter: false,
    silent: true,
  })
  await unlink(path.join(TMP_DIR, "index.proto"))

  const cssPath = path.join(TMP_DIR, CSS_FILE)
  await writeFile(
    cssPath,
    `/* ${ASSET} ${release.tag_name}, generated by ${SCRIPT} */\n` +
      (await readFile(cssPath, "utf8")),
  )
} catch (error) {
  await rm(TMP_DIR, { recursive: true, force: true })
  fail(`split failed: ${(error as Error).message}`)
}

// Once OUT_DIR is removed, TMP_DIR holds the only copy, so it must be
// preserved on interrupt
process.off("SIGINT", onInterrupt)
await rm(OUT_DIR, { recursive: true, force: true })
await rename(TMP_DIR, OUT_DIR)

const chunks = (await readdir(OUT_DIR)).filter((f) => f.endsWith(".woff2"))
let bytes = 0
for (const f of chunks) bytes += (await stat(path.join(OUT_DIR, f))).size
console.log(
  `${current ?? "none"} → ${release.tag_name}: ${chunks.length} chunks, ` +
    `${mb(bytes)} in ${path.relative(process.cwd(), OUT_DIR)}`,
)
